#!/bin/bash
# Noctis Local Test Server Deployment Script
# PRODUCTION NOTE: Run behind a reverse proxy (Nginx/Caddy) with HTTPS.
# Never expose Noctis directly on port 80/443 without TLS in production.
# Recommended: Caddy with automatic HTTPS (caddy reverse-proxy --from noctis.app --to localhost:8080)
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info()    { echo -e "${CYAN}[NOCTIS]${NC} $1"; }
log_success() { echo -e "${GREEN}[✓]${NC} $1"; }
log_warn()    { echo -e "${YELLOW}[!]${NC} $1"; }
log_error()   { echo -e "${RED}[✗] ERROR:${NC} $1"; exit 1; }

# Ensure we are always running from the project root
cd "$(dirname "$0")/.."
PROJECT_ROOT="$(pwd)"
log_info "Project root: $PROJECT_ROOT"

# ─── 1. Node 24 check ────────────────────────────────────────────────────────
required_node="24"
if ! command -v node >/dev/null 2>&1; then
  log_error "Node.js not found. Install Node 24: https://nodejs.org"
fi
actual_node=$(node -v | cut -d. -f1 | tr -d 'v')
[ "$actual_node" -lt "$required_node" ] && log_error "Node $required_node+ required. Got: $(node -v)"
log_success "Node version: $(node -v)"

# ─── 2. pnpm 10 check ────────────────────────────────────────────────────────
if ! command -v pnpm >/dev/null 2>&1; then
  log_error "pnpm not found. Install with: corepack enable && corepack prepare pnpm@10.29.3 --activate"
fi
pnpm_ver=$(pnpm -v)
[[ "$pnpm_ver" != 10* ]] && log_error "pnpm 10.x required. Got: $pnpm_ver. Run: corepack enable && corepack prepare pnpm@10.29.3 --activate"
log_success "pnpm version: $pnpm_ver"

# ─── 3. Docker check ─────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  log_error "Docker not found. Install Docker: https://docs.docker.com/engine/install/"
fi
docker info >/dev/null 2>&1 || log_error "Docker daemon not running. Start it with: sudo systemctl start docker"
log_success "Docker available"

# ─── 4. Port availability checks ─────────────────────────────────────────────
check_port() {
  local port=$1
  local service=$2
  if ss -tlnp 2>/dev/null | grep -q ":${port} " || netstat -tlnp 2>/dev/null | grep -q ":${port} "; then
    log_error "Port $port is already in use (needed for $service). Free it before continuing."
  fi
}

NOCTIS_HTTP_PORT="${NOCTIS_HTTP_PORT:-8080}"
check_port "$NOCTIS_HTTP_PORT" "Noctis web UI"
log_success "Port $NOCTIS_HTTP_PORT is free (Noctis web UI)"

# Check optional profile ports only if those profiles are being activated
PROFILES="${COMPOSE_PROFILES:-}"
if echo "$PROFILES" | grep -q "search"; then
  check_port "${MEILI_PORT:-7700}" "Meilisearch"
  log_success "Port ${MEILI_PORT:-7700} is free (Meilisearch)"
fi
if echo "$PROFILES" | grep -q "voice"; then
  check_port "${LIVEKIT_PORT:-7880}" "LiveKit"
  log_success "Port ${LIVEKIT_PORT:-7880} is free (LiveKit)"
fi

# ─── 5. .env setup ───────────────────────────────────────────────────────────
if [ ! -f "$PROJECT_ROOT/.env" ]; then
  if [ -f "$PROJECT_ROOT/.env.example" ]; then
    cp "$PROJECT_ROOT/.env.example" "$PROJECT_ROOT/.env"
    log_warn ".env created from .env.example — review it before production use"
  else
    log_warn ".env not found and no .env.example present. Creating minimal .env..."
    cat > "$PROJECT_ROOT/.env" <<EOF
# Generated by deploy_test_server.sh
MEILI_MASTER_KEY=$(openssl rand -hex 32)
NOCTIS_HTTP_PORT=8080
EOF
  fi
fi

# Auto-generate MEILI_MASTER_KEY if not set
if ! grep -q "^MEILI_MASTER_KEY=.\+" "$PROJECT_ROOT/.env" 2>/dev/null; then
  GENERATED_KEY=$(openssl rand -hex 32)
  # Append or replace the empty key line
  if grep -q "^MEILI_MASTER_KEY=" "$PROJECT_ROOT/.env"; then
    sed -i "s/^MEILI_MASTER_KEY=.*/MEILI_MASTER_KEY=${GENERATED_KEY}/" "$PROJECT_ROOT/.env"
  else
    echo "MEILI_MASTER_KEY=${GENERATED_KEY}" >> "$PROJECT_ROOT/.env"
  fi
  log_warn "Generated MEILI_MASTER_KEY in .env. Keep this secret."
fi
log_success ".env is ready"

# ─── 6. config/config.json setup ─────────────────────────────────────────────
if [ ! -f "$PROJECT_ROOT/config/config.json" ]; then
  if [ -f "$PROJECT_ROOT/scripts/dev_bootstrap.sh" ]; then
    log_info "Running dev_bootstrap.sh to generate config.json..."
    bash "$PROJECT_ROOT/scripts/dev_bootstrap.sh"
  elif [ -f "$PROJECT_ROOT/config/config.dev.template.json" ]; then
    log_warn "No dev_bootstrap.sh found. Copying config.dev.template.json as config.json — secrets will be empty, edit as needed."
    mkdir -p "$PROJECT_ROOT/config"
    cp "$PROJECT_ROOT/config/config.dev.template.json" "$PROJECT_ROOT/config/config.json"
  else
    log_error "No config/config.json and no template to copy. Cannot continue."
  fi
fi
log_success "config/config.json is present"

# ─── 7. Dependencies ─────────────────────────────────────────────────────────
log_info "Installing dependencies (frozen lockfile)..."
pnpm install --frozen-lockfile
log_success "Dependencies installed"

# ─── 8. Build ────────────────────────────────────────────────────────────────
log_info "Building all packages..."
pnpm turbo build
log_success "Build complete"

# ─── 9. Pull latest Docker images ────────────────────────────────────────────
log_info "Pulling latest Docker images..."
docker compose pull --quiet || log_warn "Could not pull some images — continuing with cached versions"
log_success "Images ready"

# ─── 10. Docker Compose up ───────────────────────────────────────────────────
log_info "Starting Noctis stack..."
docker compose up -d
log_success "Noctis stack started"

# ─── 11. Health check ────────────────────────────────────────────────────────
log_info "Waiting for Noctis to become healthy..."
HEALTH_URL="http://localhost:${NOCTIS_HTTP_PORT}/_health"
ATTEMPTS=0
MAX_ATTEMPTS=30
until curl -sf "$HEALTH_URL" >/dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
    log_error "App did not become healthy after $((MAX_ATTEMPTS * 2)) seconds. Check logs: docker compose logs noctis_server"
  fi
  sleep 2
done

echo ""
log_success "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log_success " Noctis is live at http://localhost:${NOCTIS_HTTP_PORT}"
log_success " Health: $HEALTH_URL"
log_success " Logs: docker compose logs -f"
log_success " Stop: docker compose down"
log_success "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
